# Generated by Django 4.1 on 2023-09-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userposts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpost",
            name="createdOn",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
