# Generated by Django 4.1 on 2023-10-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userposts", "0003_alter_userpost_user_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpost",
            name="file1",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="userpost",
            name="file2",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="userpost",
            name="file3",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
