# Generated by Django 4.1 on 2023-10-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
