# Generated by Django 4.1 on 2023-11-07 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0004_quiz_numofquestions_studentscore_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
