# Generated by Django 4.1 on 2023-11-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_course'),
        ('Lessons', '0005_question_questionnumber_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Education.course'),
        ),
    ]
