# Generated by Django 4.1 on 2023-11-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0006_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
