# Generated by Django 4.1 on 2023-11-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0007_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default='1', max_length=1),
        ),
    ]
