# Generated by Django 4.1 on 2023-11-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0009_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='attemptNumber',
            field=models.IntegerField(default=1),
        ),
    ]
