# Generated by Django 4.1 on 2023-11-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0010_studentscore_attemptnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscore',
            name='attemptNumber',
            field=models.IntegerField(default=3),
        ),
    ]
